# Generated by Django 5.2.5 on 2025-08-07 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='author_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='category_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
